### ISSUE TITLE
Choosing a default solver

### ISSUE THREAD

**Issue by greydanus** [fancompute/angler#32]
**Describe the bug**
I'm getting an error which is essentially ```pardisoSolver is not recognized``` inside the ```solver_direct``` function of linalg.py. It appears to be because the solver being passed as a 'solver' argument is 'paradiso' but my computer does not support pyMKL for some reason. There's a check at the head of this file in lines 5-9 for this, but I think the same check should be added to the constants.py file as well.

I traced the 'solver' parameter back and found that it was being set in constants.py. By adding a check for pyMKL in that file, I was able to make angler fall back on ```scipy``` in the way I wanted it to.

Sorry if that's not super clear ^, I'm somewhat new to filing GitHub issues. I think this is a pretty simple fix :)

**Comment by twhughes** [comment]
Thanks for letting me know Sam.  I just pushed some changes to master branch that should fix this for you.  Feel free to re-open this issue if you're still having problems :)

**Comment by twhughes** [comment]
BTW, pyMKL will not work unless MKL is installed on your computer.  I would try installing with `conda install MKL` and see if that works.
