### ISSUE TITLE
Background Index

### ISSUE THREAD

**Issue by matthewvanniekerk** [fancompute/angler#33]
Is there a way to change the background index (i.e. to an oxide or other cladding value) or is this something that would be of low usefulness? I guess since it is relative permitivitty it may not matter but it seems like that would be useful for informing a real implementation. It seems to me in your structures.py file you hard-code the background to 1 like: 

`   design_region = apply_regions([box], xs, ys, 2) - 1 `

Where maybe that could be a parameter instead of '2'. I changed that value around but the init_design_region rewrites it based on this value and I started going down the rabbit hole.

Either way, I was just curious. This project is pretty brilliant, great work!

P.S. I was working through the Splitting Jupyter Notebook after I stumbled upon this from your paper.

**Comment by twhughes** [comment]
Hey Matthew

Thanks for the question.  I just pushed an ability to add an optional `eps_background` keyward argument to the apply regions function.  See [here](https://github.com/fancompute/angler/blob/master/angler/structures.py#L32).

Perhaps this should enable you to do what you want.  Basically, the detault epsilon in the background region (where the `reg_list` evaluates to 0) will be given by this parameter and defaults to 1.

Let me know if that clears things up for you.

**Comment by twhughes** [comment]
Depending on how you're applying the `init_design_region` function, this might still overwrite it though.  Let me take a look

**Comment by twhughes** [comment]
Ok i just pushed some changes to `init_design_region` and also added the option to pass `eps_background` to `3_port` in `structures.py`.  Tested it and it seems to work ok.  Hope it helps!

**Comment by matthewvanniekerk** [comment]
Awesome! Seems to work with mine too, thanks. I'm excited to keep playing with this tool.

**Comment by twhughes** [comment]
glad you like it!  We're thinking about revamping it at some point.  Maybe using pytorch and automatic differentiation, so stay tuned!
