### ISSUE TITLE
Angler 2.0

### ISSUE THREAD

**Issue by twhughes** [fancompute/angler#35]
- [ ] - Autograd **EVERYTHING**
- [ ] - Make low pass filter faster.
- [ ] - Change the way objective functions are created (like in ceviche) to be more flexible.
- [ ] - Clean up code.  Instead of conditionals / switches, lets try to make it more clean.

**Comment by Roan2117** [comment]
Dear
How do I can plot power transmission in a output port?
for example in a splitter..

**Comment by twhughes** [comment]
Hi @Roan2117 
There's no way to do this in the current version of the code.  However, if you make a fork  or local copy of angler, you could simply add some code to do this.
For example, if running a gradient descent optimizer, you could compute the power transmission in [here](https://github.com/fancompute/angler/blob/master/angler/optimization.py#L224) and append to a list.

Also, if your objective function happens to be the power transmission, then the transmission vs. iteration is stored in `Optimization.objfn_list`.  For example, this attribute is updated on  [this line](https://github.com/fancompute/angler/blob/master/angler/optimization.py#L223)

**Comment by Roan2117** [comment]
Thank you for your answer
