### ISSUE TITLE
Acoustic Simulation / Optimization

### ISSUE THREAD

**Issue by lolz0r** [fancompute/angler#38]
I am seeking a software package that can assist in developing more sophisticated acoustic lenses and systems for acoustic levitation. Is there any plan to adapt this system to be able to run in the acoustic domain?

**Comment by ianwilliamson** [comment]
Hi, you might be interested in a related package/paper of ours available here: https://github.com/fancompute/wavetorch/

The wavetorch package simulates and computes gradients of a scalar wave equation PDE, which is closer to the physics you seem to be interested in. The package is based on pytorch, and is more oriented around machine learning tasks, but it could also be easily used for more conventional inverse design optimizations.

**Comment by lolz0r** [comment]
Very nice! Thank you!

**Comment by ianwilliamson** [comment]
Specifically, you can check out this example: https://github.com/fancompute/wavetorch/blob/master/study/optimize_lens.py
