### ISSUE TITLE
simulation.setup_modes() error

### ISSUE THREAD

**Issue by drmcnelson** [fancompute/angler#39]
**Describe the bug**

dl 5
eps_r.shape (700, 140)
NPML [15, 15] polarization Ez
modalsrc at coords 458,120 width 100 neff (3.5+0j)

Traceback (most recent call last):
  File "../FDFDmodel/FDFDmodel.py", line 491, in <module>
    simulation.setup_modes()
  File "/usr/local/lib/python3.7/site-packages/angler/simulation.py", line 60, in setup_modes
    modei.setup_src(self)
  File "/usr/local/lib/python3.7/site-packages/angler/source/mode.py", line 21, in setup_src
    self.compute_normalization(simulation, matrix_format=matrix_format)
  File "/usr/local/lib/python3.7/site-packages/angler/source/mode.py", line 55, in compute_normalization
    W_in = simulation_norm.flux_probe(self.direction_normal, new_center, self.width)
  File "/usr/local/lib/python3.7/site-packages/angler/simulation.py", line 278, in flux_probe
    Sx = -1/2*np.real(Ez_x*np.conj(field_val_Hy[inds_x[0]:inds_x[1], inds_y[0]:inds_y[1]]))
ValueError: operands could not be broadcast together with shapes (1,69) (1,70) 
[

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]   Linux Fedora 30

**Smartphone (please complete the following information):**

**Additional context**

Python 3

**Comment by momchilmm** [comment]
It seems that your modal source extends beyond the simulation domain. The default normal direction (i.e. propagating direction) for the modal source is x, i.e. a source at position [458, 120] with width 100 extends from [458, 70] to [458, 170], while your `eps_r` array only goes to 140 in the second dimension (y).

**Comment by twhughes** [comment]
Hi @drmcnelson, thanks for raising the issue.  In the future we will update the mode calculation tool and catch issues like this, including more helpful error messages.  For now, just make sure the `width` of the mode object does not extend over the edge of the domain.  Closing for now
