### ISSUE TITLE
Least Squares Definiton for Objective Function

### ISSUE THREAD

**Issue by aonurdasdemir** [fancompute/angler#40]
Hi,

I see that you are implementing the objective function by multiplying the overlap in each port for the 4-Splitter demo. I understand that this works well but multiplying does not seem as a general method to me. For example, when you would want to reach different overlap values in each port, you would implement the objective function like least squares method and minimize it. I believe that for two outputs, it would be:
objective_function = (port1_obj - 0.3)^2 + (port2_obj - 0.7)^2
This would make the objective in port_1 0.3 and port_2 0.7 when the sum is minimum.

So, is there a specific reason that you considered multiplication instead of a more general method like least squares? 

Thank you.

**Comment by twhughes** [comment]
There's no particular reason, this was simply an example of one way to write down and objective function.  The way you have it written would work perfectly well too.  Note that yours would be sensitive to the phase in the ports, just something to keep in mind.
